fail_fast: true
repos:
  - repo: https://github.com/ambv/black
    rev: "20.8b1"
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pycqa/pylint
    rev: "pylint-2.7.2"
    hooks:
      - id: pylint
        entry: pylint --rcfile=.pylintrc
        additional_dependencies: ["packaging"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.770"
    hooks:
      - id: mypy
